smetric cipher fixes
	modified:   src/card_os/constants.h
	modified:   src/card_os/fs.c
	modified:   src/card_os/iso7816.c
	modified:   src/card_os/iso7816.h
	modified:   src/card_os/myeid_emu.c
	modified:   tools/OsEID-tool

diff --git a/tools/OsEID-tool b/tools/OsEID-tool
--- a/tools/OsEID-tool
+++ b/tools/OsEID-tool
@@ -4,7 +4,7 @@
 #
 #    This is part of OsEID (Open source Electronic ID)
 #
-#    Copyright (C) 2015-2020 Peter Popovec, popovec.peter@gmail.com
+#    Copyright (C) 2015-2021 Peter Popovec, popovec.peter@gmail.com
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -39,13 +39,15 @@ warnecho (){
 
 mechanism2hash () {
 	case "${1}" in
-	"SHA1-RSA-PKCS"|"SHA1-RSA-PKCS-PSS")
+	"SHA1-RSA-PKCS"|"SHA1-RSA-PKCS-PSS"|"ECDSA-SHA1")
 		echo "sha1";;
-	"SHA256-RSA-PKCS"|"SHA256-RSA-PKCS-PSS")
+	"SHA224-RSA-PKCS"|"SHA224-RSA-PKCS-PSS"|"ECDSA-SHA224")
+		echo "sha224";;
+	"SHA256-RSA-PKCS"|"SHA256-RSA-PKCS-PSS"|"ECDSA-SHA256")
 		echo "sha256";;
-	"SHA384-RSA-PKCS"|"SHA384-RSA-PKCS-PSS")
+	"SHA384-RSA-PKCS"|"SHA384-RSA-PKCS-PSS"|"ECDSA-SHA384")
 		echo "sha384";;
-	"SHA512-RSA-PKCS"|"SHA512-RSA-PKCS-PSS")
+	"SHA512-RSA-PKCS"|"SHA512-RSA-PKCS-PSS"|"ECDSA-SHA512")
 		echo "sha512";;
 	*)
 		echo "${1}";;
@@ -140,6 +142,7 @@ else
 	echo "EC-UPLOAD-KEYS - upload EC keys into initialized token"
 	echo "EC-GENERATE-KEYS  - generate keys on card" 
 	echo "EC-SIGN-TEST - sign sample text by ECDSA operation and verify this signature"
+	echo "EC-SIGN-PKCS11-TEST - sign (pkcs11-tool, several mechanisms), check results"
 	echo "EC-ECDH-TEST - generate shared secrets and test shared secrets "
 	echo "RSA-CREATE-KEYS -  use openssl to generate RSA keys"
 	echo "RSA-UPLOAD-KEYS - upload RSA keys into initialized token"
@@ -428,8 +431,9 @@ if [ $mode == "FULL-TEST" ]; then
 	# OsEID card is slow, skip this test for now
 	# $0 RSA-GENERATE-KEYS 1024
 	$0 RSA-SIGN-TEST
-	$0 RSA-SIGN-TEST
-	$0 RSA-SIGN-PKCS11-TEST
+	if [ "x${2}" == "xpkcs11" ]; then
+		$0 RSA-SIGN-PKCS11-TEST
+	fi
 	$0 RSA-DECRYPT-TEST
 
 	$0 ERASE-CARD
@@ -437,6 +441,7 @@ if [ $mode == "FULL-TEST" ]; then
 	$0 EC-UPLOAD-KEYS
 	$0 EC-GENERATE-KEYS
 	$0 EC-SIGN-TEST
+	# $0 EC-SIGN-PKCS11-TEST
 	$0 EC-ECDH-TEST
 
 	$0 DES-AES-UPLOAD-KEYS
@@ -499,10 +504,10 @@ if [ $CARD_TYPE == "OsEID" ]; then
 fi
 #***************************************************************************************************************************
 if [ $mode == "ERASE-CARD" ]; then
-	read_card "00 20 00 03 08 30 30 30 30 30 30 30 30" "${SCReaderFlag}" "${SCReader}" >/dev/null
-	read_card "00 DA 01 E0 08 FF FF 11 3F FF 11 1F FF" "${SCReaderFlag}" "${SCReader}" >/dev/null
-# TODO this is not working if stdout is redirected
-#	echo "00000000"|PKCS15-INIT -E
+	opensc-tool "${SCReaderFlag}" "${SCReader}" -c default -s "00 20 00 03 08 30 30 30 30 30 30 30 30" -s "00 DA 01 E0 08 FF FF 11 3F FF 11 1F FF"
+
+# pkcs15-tool -E need tty (ioctl to not display pin)..
+#	(echo "00000000"|  PKCS15-INIT -E >/dev/tty) >/dev/null
 #	if [ $? -eq 0 ];then
 #		trueecho "Card is erased"
 #	else
@@ -598,15 +603,19 @@ while read keyID ; do
   echo "Reading public key "$keyID
   PKCS15-TOOL --read-public-key $keyID |tee tmp/exported_ec_key.pub
   echo "generating plain sha1 hash file:"
-  echo "test" > tmp/testfile.txt
-  echo  "create sha1 hash of testing file in binary form:"
+  echo "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest" > tmp/testfile.txt
+  echo "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest" >> tmp/testfile.txt
+  echo "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest" >> tmp/testfile.txt
+  echo "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest" >> tmp/testfile.txt
+  # we use openssl dgst to verify signature, hash is needed for sign...
   sha1sum tmp/testfile.txt|cut -d ' ' -f 1|xxd -p -r > tmp/testfile.txt.sha1
-  echo "generating signature by pkcs15-crypt"
+
+  echo "generating RAW ECDSA signature by pkcs15-crypt"
   rm -f tmp/testfile.txt.pkcs11.sha1.sig
   ST=`date +%s.%N`
   PKCS15-CRYPT --pin 11111111 -k $keyID --signature-format "openssl" -s -i tmp/testfile.txt.sha1 -o tmp/testfile.txt.pkcs11.sha1.sig
   if [ $? -ne 0 ]; then
-	failecho "pkcs11-tool failed"
+	failecho "pkcs15-crypt failed"
 	exit 1
   fi
   ET=`date +%s.%N`
@@ -617,31 +626,114 @@ while read keyID ; do
 	failecho "openssl signature test fail"
 	exit 1
   fi
-  rm -f tmp/testfile.txt.pkcs11.sha1.sig
-  echo "generating signature by pkcs11-tool"
+
+done # key loop
+fi
+
+# pkcs11-tool:
+# there is no differense in -m ECDSA or -m ECDSA-SHA1 .. card always get same input (OpenSC bug...)
+# pkcs11-tool --sign --signature-format "openssl" --slot 1 -m ECDSA --input-file sign.this.txt --output-file sign.this.txt.signature
+# pkcs11-tool --sign --signature-format "openssl" --slot 1 -m ECDSA-SHA1 --input-file sign.this.txt --output-file sign.this.txt.signature
+
+#***************************************************************************************************************************
+if [ $mode == "EC-SIGN-PKCS11-TEST" ]; then
+mkdir -p tmp
+
+ECC_SIZE_TEST=`pkcs11-tool --slot-index ${SCSlot} -M 2>/dev/null`
+ECC_SIZE_MAX=0
+echo ${ECC_SIZE_TEST}|grep -q -F -e 'ECDSA-SHA1' && ECC_SIZE_MAX=256
+if [ $ECC_SIZE_MAX -eq 0 ]; then warnecho "card does not support EC funcfions";exit 0;fi
+echo ${ECC_SIZE_TEST}|grep -q -F -e 'ECDSA-SHA1, keySize={192,384}' && ECC_SIZE_MAX=384
+echo ${ECC_SIZE_TEST}|grep -q -F -e 'ECDSA-SHA1, keySize={192,521}' && ECC_SIZE_MAX=521
+
+echo "Testing ECDSA"
+echo "-------------"
+PKCS15-TOOL --list-public-keys|\
+gawk -v SIZE=$ECC_SIZE_MAX -F: '{if($1 ~ "FieldLength"){if(strtonum($2)<=SIZE){OK=1;fl=$2}else OK=0}if($1~"ID" && OK==1){print $2" "fl;OK=0}}' |\
+while read keyID fl; do
+  bfl=$[$fl + 7 ]
+  bfl=$[bfl / 8 ]
+  echo "Reading public key ${keyID}  field length=${fl} (${bfl} bytes)"
+
+  PKCS15-TOOL --read-public-key $keyID > tmp/exported_ec_key.pub
+
+  echo "pkcs11-tool sign and pkcs11-tools --verify"
+
+  echo "test" > tmp/testfile.txt
+  rm -f tmp/testfile.txt.pkcs11.sig
   ST=`date +%s.%N`
-  pkcs11-tool --slot-index ${SCSlot} --pin 11111111 --sign --signature-format "openssl"  -m ECDSA --input-file tmp/testfile.txt.sha1 --output-file tmp/testfile.txt.pkcs11.sha1.sig --id $keyID
+  pkcs11-tool --slot-index ${SCSlot} --pin 11111111 --sign  -m ECDSA --signature-format "sequence" --input-file tmp/testfile.txt --output-file tmp/testfile.txt.pkcs11.sig --id $keyID
   if [ $? -ne 0 ]; then
 	failecho "pkcs11-tool failed"
 	exit 1
   fi
   ET=`date +%s.%N`
   echo "${ET} ${ST}"|gawk '{printf "pkcs11-tool EC SIGN time %f\n",($1 - $2)}'
-  echo "testing signature.."
+
+  pkcs11-tool --slot-index ${SCSlot} --verify -m ECDSA  --signature-format "sequence" --input-file tmp/testfile.txt --signature-file tmp/testfile.txt.pkcs11.sig --id $keyID|grep -q "^Signature is valid$"
+  if [ $? -ne 0 ]; then
+	failecho "openssl signature test fail"
+	exit 1
+  else
+	trueecho "Verified OK"
+  fi
+  echo "pkcs11-tool sign and openssl verify"
+  # we using openssl dgst we need to sign digest ..
+  echo "generating plain sha1 hash file:"
+  echo "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest" > tmp/testfile.txt
+  echo "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest" >> tmp/testfile.txt
+  echo "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest" >> tmp/testfile.txt
+  echo "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest" >> tmp/testfile.txt
+  # we use openssl dgst to verify signature, hash is needed for sign...
+  sha1sum tmp/testfile.txt|cut -d ' ' -f 1|xxd -p -r > tmp/testfile.txt.sha1
+
+  rm -f tmp/testfile.txt.pkcs11.sha1.sig
+  echo "generating RAW ECDSA signature by pkcs11-tool $bfl"
+  rm -f tmp/testfile.txt.pkcs11.sha1.sig
+  pkcs11-tool --slot-index ${SCSlot} --pin 11111111 --sign  -m ECDSA --signature-format "openssl" --input-file tmp/testfile.txt.sha1 --output-file tmp/testfile.txt.pkcs11.sha1.sig --id $keyID
+  if [ $? -ne 0 ]; then
+	failecho "pkcs11-tool failed"
+	exit 1
+  fi
+  echo "testing signature.. (openssl)"
   openssl dgst -sha1 -verify tmp/exported_ec_key.pub -signature tmp/testfile.txt.pkcs11.sha1.sig tmp/testfile.txt
   if [ $? -ne 0 ]; then
 	failecho "openssl signature test fail"
 	exit 1
+  else
+	trueecho "Verified OK"
   fi
-done
+
+  for d in sha1 sha224 sha256 sha384 sha512 ; do
+	D=`echo ${d}|tr [:lower:] [:upper:]`
+	rm -f tmp/testfile.txt.pkcs11.${d}.sig
+	# pkcs11 operation corresponds to:
+	# openssl dgst -sha1 -sign keys/secp384r1-key.pem -out tmp/testfile.txt.pkcs11.sha1.sig tmp/testfile.txt
+	pkcs11-tool --slot-index ${SCSlot} --pin 11111111 --sign --signature-format "openssl" -m ECDSA-${D} --input-file tmp/testfile.txt --output-file tmp/testfile.txt.pkcs11.${d}.sig --id $keyID
+	if [ $? -ne 0 ]; then
+		failecho "pkcs11-tool failed"
+		exit 1
+	fi
+	echo "testing ECDSA-${D} signature (openssl)"
+	openssl dgst -${d} -verify tmp/exported_ec_key.pub -signature tmp/testfile.txt.pkcs11.${d}.sig tmp/testfile.txt
+	if [ $? -ne 0 ]; then
+		failecho "openssl signature test fail"
+		exit 1
+	else
+		trueecho "Verified OK"
+	fi
+	echo "testing ECDSA-${D} signature.. (pkcs11-tool)"
+	pkcs11-tool --slot-index ${SCSlot} --verify  --signature-format "openssl" -m ECDSA-${D} --id $keyID --input-file tmp/testfile.txt --signature-file tmp/testfile.txt.pkcs11.${d}.sig|grep -q "^Signature is valid$"
+	if [ $? -ne 0 ]; then
+		failecho "pkcs11-tool --verify failed"
+		exit 1
+	else
+		trueecho "Verified OK"
+	fi
+  done # digest loop
+done # key loop
 exit $?
 fi
-
-# pkcs11-tool:
-# there is no differense in -m ECDSA or -m ECDSA-SHA1 .. card always get same input
-# pkcs11-tool --sign --signature-format "openssl" --slot 1 -m ECDSA --input-file sign.this.txt --output-file sign.this.txt.signature
-# pkcs11-tool --sign --signature-format "openssl" --slot 1 -m ECDSA-SHA1 --input-file sign.this.txt --output-file sign.this.txt.signature
-
 #***************************************************************************************************************************
 
 
@@ -968,15 +1060,25 @@ if [ $? -eq 0 ]; then
 #	openssl rsautl -raw -verify -pubin -inkey tmp/exported_rsa_key.pub < tmp/rsa_sign_testfile.txt.sign |hd
 	openssl dgst "-${file_hash}" -verify tmp/exported_rsa_key.pub -signature tmp/rsa_sign_testfile.txt.sign tmp/rsa_sign_testfile.txt
 	if [ $?	-ne 0 ]; then
-		failecho "openssl signature test fail - ignoring because old opensc"
-		#err=$[$err + 1 ]
+		failecho "openssl signature test fail"
+		err=$[$err + 1 ]
 	else
 		trueecho "Verified OK"
 	fi
+	echo "sinature verification by pkcs11-tool"
+	pkcs11-tool --slot-index ${SCSlot} --verify  -m "${MECHANISM}" --id $keyID --input-file tmp/rsa_sign_testfile.txt --signature-file tmp/rsa_sign_testfile.txt.sign|grep -q "^Signature is valid$"
+	if [ $? -ne 0 ]; then
+		failecho "pkcs11-tool --verify failed"
+		err=$[$err + 1 ]
+	else
+		trueecho "Verified OK"
+	fi
+
 else
-	failecho "pkcs11 fail - ignoring because old opensc"
-	#err=$[$err + 1 ]
+	failecho "pkcs11 fail"
+	err=$[$err + 1 ]
 fi
+
 done	# mechanism loop (no PSS mechanisms)
 
 
@@ -1008,14 +1110,22 @@ if [ $? -eq 0 ]; then
 		 -pkeyopt digest:${file_hash} \
 		 -pubin -inkey tmp/exported_rsa_key.pub
 	if [ $?	-ne 0 ]; then
-		failecho "openssl signature test fail, ignoring because old opensc"
-		#err=$[$err + 1 ]
+		failecho "openssl signature test fail"
+		err=$[$err + 1 ]
 	else
 		trueecho "Verified OK"
 	fi
+	echo "sinature verification by pkcs11-tool"
+	pkcs11-tool --slot-index ${SCSlot} --verify  -m "${MECHANISM}" --id $keyID --input-file tmp/rsa_sign_testfile.txt --signature-file tmp/rsa_sign_testfile.txt.${file_hash}.sign|grep -q "^Signature is valid$"
+	if [ $? -ne 0 ]; then
+		failecho "pkcs11-tool --verify failed"
+		err=$[$err + 1 ]
+        else
+		trueecho "Verified OK"
+	fi
 else
-	failecho "pkcs11 fail - ignoring because old opensc"
-	#err=$[$err + 1 ]
+	failecho "pkcs11 fail"
+	err=$[$err + 1 ]
 fi
 done # mechanism loop (PSS mechanisms)
 done    # key loop
@@ -1133,8 +1243,20 @@ if [ $mode == "DES-AES-UPLOAD-KEYS" ]; then
 		failecho "Symetric key upload: ${err} errors!"
 		exit 1
 	fi
-
 	exit 0
+fi
+if [ $mode == "AES-TEST" ]; then
+	echo -n "01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 20"|xxd -p -r > tmp/carblue.key
+	$0 ERASE-CARD
+	echo "" |$0 INIT
+	PKCS15-INIT --store-secret-key tmp/carblue.key --secret-key-algorithm aes256   --auth-id 01  --pin=11111111 --id 89
+	pkcs11-tool --test --login --pin 11111111 |tee /dev/tty|grep -q "No error"
+	if [ $? -eq 0 ]; then
+		trueecho "OK"
+	else
+	        failecho "AES test failed"
+		exit 1
+	fi
 fi
 #***************************************************************************************************************************
 # compatibility with old version ...
